document.createElement("canvas").getContext||function(){function G(){return this.context_||(this.context_=new v(this))}function H(a,b){var c=z.call(arguments,2);return function(){return a.apply(b,c.concat(z.call(arguments)))}}function I(a){var b=a.srcElement;switch(a.propertyName){case "width":b.style.width=b.attributes.width.nodeValue+"px";b.getContext().clearRect();break;case "height":b.style.height=b.attributes.height.nodeValue+"px",b.getContext().clearRect()}}function J(a){a=a.srcElement;if(a.firstChild)a.firstChild.style.width=
a.clientWidth+"px",a.firstChild.style.height=a.clientHeight+"px"}function w(){return[[1,0,0],[0,1,0],[0,0,1]]}function n(a,b){for(var c=w(),d=0;d<3;d++)for(var e=0;e<3;e++){for(var f=0,h=0;h<3;h++)f+=a[d][h]*b[h][e];c[d][e]=f}return c}function A(a,b){b.fillStyle=a.fillStyle;b.lineCap=a.lineCap;b.lineJoin=a.lineJoin;b.lineWidth=a.lineWidth;b.miterLimit=a.miterLimit;b.shadowBlur=a.shadowBlur;b.shadowColor=a.shadowColor;b.shadowOffsetX=a.shadowOffsetX;b.shadowOffsetY=a.shadowOffsetY;b.strokeStyle=a.strokeStyle;
b.globalAlpha=a.globalAlpha;b.arcScaleX_=a.arcScaleX_;b.arcScaleY_=a.arcScaleY_;b.lineScale_=a.lineScale_}function B(a){var b,c=1;a=String(a);if(a.substring(0,3)=="rgb"){b=a.indexOf("(",3);var d=a.indexOf(")",b+1);d=a.substring(b+1,d).split(",");b="#";for(var e=0;e<3;e++)b+=C[Number(d[e])];d.length==4&&a.substr(3,1)=="a"&&(c=d[3])}else b=a;return{color:b,alpha:c}}function K(a){switch(a){case "butt":return"flat";case "round":return"round";default:return"square"}}function v(a){this.m_=w();this.mStack_=
[];this.aStack_=[];this.currentPath_=[];this.fillStyle=this.strokeStyle="#000";this.lineWidth=1;this.lineJoin="miter";this.lineCap="butt";this.miterLimit=j*1;this.globalAlpha=1;this.canvas=a;var b=a.ownerDocument.createElement("div");b.style.width=a.clientWidth+"px";b.style.height=a.clientHeight+"px";b.style.overflow="hidden";b.style.position="absolute";a.appendChild(b);this.element_=b;this.lineScale_=this.arcScaleY_=this.arcScaleX_=1}function D(a,b,c,d){a.currentPath_.push({type:"bezierCurveTo",
cp1x:b.x,cp1y:b.y,cp2x:c.x,cp2y:c.y,x:d.x,y:d.y});a.currentX_=d.x;a.currentY_=d.y}function o(a,b,c){var d;a:{for(d=0;d<3;d++)for(var e=0;e<2;e++)if(!isFinite(b[d][e])||isNaN(b[d][e])){d=!1;break a}d=!0}if(d&&(a.m_=b,c))a.lineScale_=L(M(b[0][0]*b[1][1]-b[0][1]*b[1][0]))}function q(a){this.type_=a;this.r1_=this.y1_=this.x1_=this.r0_=this.y0_=this.x0_=0;this.colors_=[]}function E(){}var p=Math,i=p.round,x=p.sin,y=p.cos,M=p.abs,L=p.sqrt,j=10,l=j/2,z=Array.prototype.slice,F={init:function(a){/MSIE/.test(navigator.userAgent)&&
!window.opera&&(a=a||document,a.createElement("canvas"),a.attachEvent("onreadystatechange",H(this.init_,this,a)))},init_:function(a){a.namespaces.g_vml_||a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML");a.namespaces.g_o_||a.namespaces.add("g_o_","urn:schemas-microsoft-com:office:office","#default#VML");if(!a.styleSheets.ex_canvas_){var b=a.createStyleSheet();b.owningElement.id="ex_canvas_";b.cssText="canvas{display:inline-block;overflow:hidden;text-align:left;width:300px;height:150px}g_vml_\\:*{behavior:url(#default#VML)}g_o_\\:*{behavior:url(#default#VML)}"}a=
a.getElementsByTagName("canvas");for(b=0;b<a.length;b++)this.initElement(a[b])},initElement:function(a){if(!a.getContext){a.getContext=G;a.innerHTML="";a.attachEvent("onpropertychange",I);a.attachEvent("onresize",J);var b=a.attributes;b.width&&b.width.specified?a.style.width=b.width.nodeValue+"px":a.width=a.clientWidth;b.height&&b.height.specified?a.style.height=b.height.nodeValue+"px":a.height=a.clientHeight}return a}};F.init();for(var C=[],f=0;f<16;f++)for(var r=0;r<16;r++)C[f*16+r]=f.toString(16)+
r.toString(16);f=v.prototype;f.clearRect=function(){this.element_.innerHTML=""};f.beginPath=function(){this.currentPath_=[]};f.moveTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"moveTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};f.lineTo=function(a,b){var c=this.getCoords_(a,b);this.currentPath_.push({type:"lineTo",x:c.x,y:c.y});this.currentX_=c.x;this.currentY_=c.y};f.bezierCurveTo=function(a,b,c,d,e,f){e=this.getCoords_(e,f);a=this.getCoords_(a,b);c=this.getCoords_(c,
d);D(this,a,c,e)};f.quadraticCurveTo=function(a,b,c,d){a=this.getCoords_(a,b);c=this.getCoords_(c,d);d={x:this.currentX_+2/3*(a.x-this.currentX_),y:this.currentY_+2/3*(a.y-this.currentY_)};D(this,d,{x:d.x+(c.x-this.currentX_)/3,y:d.y+(c.y-this.currentY_)/3},c)};f.arc=function(a,b,c,d,e,f){c*=j;var h=f?"at":"wa",g=a+y(d)*c-l,i=b+x(d)*c-l;d=a+y(e)*c-l;e=b+x(e)*c-l;g==d&&!f&&(g+=0.125);a=this.getCoords_(a,b);g=this.getCoords_(g,i);d=this.getCoords_(d,e);this.currentPath_.push({type:h,x:a.x,y:a.y,radius:c,
xStart:g.x,yStart:g.y,xEnd:d.x,yEnd:d.y})};f.rect=function(a,b,c,d){this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath()};f.strokeRect=function(a,b,c,d){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,b+d);this.closePath();this.stroke();this.currentPath_=e};f.fillRect=function(a,b,c,d){var e=this.currentPath_;this.beginPath();this.moveTo(a,b);this.lineTo(a+c,b);this.lineTo(a+c,b+d);this.lineTo(a,
b+d);this.closePath();this.fill();this.currentPath_=e};f.createLinearGradient=function(a,b,c,d){var e=new q("gradient");e.x0_=a;e.y0_=b;e.x1_=c;e.y1_=d;return e};f.createRadialGradient=function(a,b,c,d,e,f){var h=new q("gradientradial");h.x0_=a;h.y0_=b;h.r0_=c;h.x1_=d;h.y1_=e;h.r1_=f;return h};f.drawImage=function(a){var b,c,d,e,f,h,g,m;d=a.runtimeStyle.width;e=a.runtimeStyle.height;a.runtimeStyle.width="auto";a.runtimeStyle.height="auto";var s=a.width,t=a.height;a.runtimeStyle.width=d;a.runtimeStyle.height=
e;if(arguments.length==3)b=arguments[1],c=arguments[2],f=h=0,g=d=s,m=e=t;else if(arguments.length==5)b=arguments[1],c=arguments[2],d=arguments[3],e=arguments[4],f=h=0,g=s,m=t;else if(arguments.length==9)f=arguments[1],h=arguments[2],g=arguments[3],m=arguments[4],b=arguments[5],c=arguments[6],d=arguments[7],e=arguments[8];else throw Error("Invalid number of arguments");var k=this.getCoords_(b,c),u=[];u.push(" <g_vml_:group",' coordsize="',j*10,",",j*10,'"',' coordorigin="0,0"',' style="width:',10,
"px;height:",10,"px;position:absolute;");if(this.m_[0][0]!=1||this.m_[0][1]){var l=[];l.push("M11=",this.m_[0][0],",","M12=",this.m_[1][0],",","M21=",this.m_[0][1],",","M22=",this.m_[1][1],",","Dx=",i(k.x/j),",","Dy=",i(k.y/j),"");var n=this.getCoords_(b+d,c),o=this.getCoords_(b,c+e);b=this.getCoords_(b+d,c+e);k.x=p.max(k.x,n.x,o.x,b.x);k.y=p.max(k.y,n.y,o.y,b.y);u.push("padding:0 ",i(k.x/j),"px ",i(k.y/j),"px 0;filter:progid:DXImageTransform.Microsoft.Matrix(",l.join(""),", sizingmethod='clip');")}else u.push("top:",
i(k.y/j),"px;left:",i(k.x/j),"px;");u.push(' ">','<g_vml_:image src="',a.src,'"',' style="width:',j*d,"px;"," height:",j*e,'px;"',' cropleft="',f/s,'"',' croptop="',h/t,'"',' cropright="',(s-f-g)/s,'"',' cropbottom="',(t-h-m)/t,'"'," />","</g_vml_:group>");this.element_.insertAdjacentHTML("BeforeEnd",u.join(""))};f.stroke=function(a){var b=[],c=B(a?this.fillStyle:this.strokeStyle),d=c.color;c=c.alpha*this.globalAlpha;b.push("<g_vml_:shape",' filled="',!!a,'"',' style="position:absolute;width:',10,
"px;height:",10,'px;"',' coordorigin="0 0" coordsize="',j*10," ",j*10,'"',' stroked="',!a,'"',' path="');for(var e={x:null,y:null},f={x:null,y:null},h=0;h<this.currentPath_.length;h++){var g=this.currentPath_[h];switch(g.type){case "moveTo":b.push(" m ",i(g.x),",",i(g.y));break;case "lineTo":b.push(" l ",i(g.x),",",i(g.y));break;case "close":b.push(" x ");g=null;break;case "bezierCurveTo":b.push(" c ",i(g.cp1x),",",i(g.cp1y),",",i(g.cp2x),",",i(g.cp2y),",",i(g.x),",",i(g.y));break;case "at":case "wa":b.push(" ",
g.type," ",i(g.x-this.arcScaleX_*g.radius),",",i(g.y-this.arcScaleY_*g.radius)," ",i(g.x+this.arcScaleX_*g.radius),",",i(g.y+this.arcScaleY_*g.radius)," ",i(g.xStart),",",i(g.yStart)," ",i(g.xEnd),",",i(g.yEnd))}if(g){if(e.x==null||g.x<e.x)e.x=g.x;if(f.x==null||g.x>f.x)f.x=g.x;if(e.y==null||g.y<e.y)e.y=g.y;if(f.y==null||g.y>f.y)f.y=g.y}}b.push(' ">');if(a)if(typeof this.fillStyle=="object"){d=this.fillStyle;g=0;a={x:0,y:0};c=0;var m=1;d.type_=="gradient"?(g=d.x1_/this.arcScaleX_,e=d.y1_/this.arcScaleY_,
h=this.getCoords_(d.x0_/this.arcScaleX_,d.y0_/this.arcScaleY_),g=this.getCoords_(g,e),g=Math.atan2(g.x-h.x,g.y-h.y)*180/Math.PI,g<0&&(g+=360),g<1.0E-6&&(g=0)):(h=this.getCoords_(d.x0_,d.y0_),c=f.x-e.x,m=f.y-e.y,a={x:(h.x-e.x)/c,y:(h.y-e.y)/m},c/=this.arcScaleX_*j,m/=this.arcScaleY_*j,h=p.max(c,m),c=2*d.r0_/h,m=2*d.r1_/h-c);e=d.colors_;e.sort(function(a,b){return a.offset-b.offset});f=e.length;var l=e[0].color,n=e[f-1].color,k=e[0].alpha*this.globalAlpha,o=e[f-1].alpha*this.globalAlpha,q=[];for(h=
0;h<f;h++){var r=e[h];q.push(r.offset*m+c+" "+r.color)}b.push('<g_vml_:fill type="',d.type_,'"',' method="none" focus="100%"',' color="',l,'"',' color2="',n,'"',' colors="',q.join(","),'"',' opacity="',o,'"',' g_o_:opacity2="',k,'"',' angle="',g,'"',' focusposition="',a.x,",",a.y,'" />')}else b.push('<g_vml_:fill color="',d,'" opacity="',c,'" />');else a=this.lineScale_*this.lineWidth,a<1&&(c*=a),b.push("<g_vml_:stroke",' opacity="',c,'"',' joinstyle="',this.lineJoin,'"',' miterlimit="',this.miterLimit,
'"',' endcap="',K(this.lineCap),'"',' weight="',a,'px"',' color="',d,'" />');b.push("</g_vml_:shape>");this.element_.insertAdjacentHTML("beforeEnd",b.join(""))};f.fill=function(){this.stroke(!0)};f.closePath=function(){this.currentPath_.push({type:"close"})};f.getCoords_=function(a,b){var c=this.m_;return{x:j*(a*c[0][0]+b*c[1][0]+c[2][0])-l,y:j*(a*c[0][1]+b*c[1][1]+c[2][1])-l}};f.save=function(){var a={};A(this,a);this.aStack_.push(a);this.mStack_.push(this.m_);this.m_=n(w(),this.m_)};f.restore=function(){A(this.aStack_.pop(),
this);this.m_=this.mStack_.pop()};f.translate=function(a,b){o(this,n([[1,0,0],[0,1,0],[a,b,1]],this.m_),!1)};f.rotate=function(a){var b=y(a);a=x(a);o(this,n([[b,a,0],[-a,b,0],[0,0,1]],this.m_),!1)};f.scale=function(a,b){this.arcScaleX_*=a;this.arcScaleY_*=b;o(this,n([[a,0,0],[0,b,0],[0,0,1]],this.m_),!0)};f.transform=function(a,b,c,d,e,f){o(this,n([[a,b,0],[c,d,0],[e,f,1]],this.m_),!0)};f.setTransform=function(a,b,c,d,e,f){o(this,[[a,b,0],[c,d,0],[e,f,1]],!0)};f.clip=function(){};f.arcTo=function(){};
f.createPattern=function(){return new E};q.prototype.addColorStop=function(a,b){b=B(b);this.colors_.push({offset:a,color:b.color,alpha:b.alpha})};G_vmlCanvasManager=F;CanvasRenderingContext2D=v;CanvasGradient=q;CanvasPattern=E}();
